name: pulzion23
description: Official App for Pulzion 23

publish_to: "none"

version: 1.2.12+12

environment:
    sdk: ">=2.18.2 <3.0.0"

dependencies:
    csc_picker: ^0.2.7
    flutter:
        sdk: flutter


    cupertino_icons: ^1.0.2

    bloc: ^8.1.0
    # flutter_spinkit: ^5.1.0
    flutter_bloc: ^8.1.1
    http: ^0.13.5
    firebase_remote_config: ^4.0.0
    firebase_core: ^2.4.1
    lottie: ^2.2.0
    flutter_svg: any
    intl: ^0.18.1
    curved_navigation_bar: ^1.0.3
    # panorama: ^0.4.1
    sizer: ^2.0.15
    firebase_messaging: ^14.2.2
    flutter_local_notifications: ^13.0.0
    flutter_secure_storage: ^8.0.0
    font_awesome_flutter: ^10.4.0
    widget_circular_animator: ^1.0.0
    flutter_staggered_animations: ^1.1.1
    countup: ^0.1.4
    url_launcher: ^6.1.9
    logger: ^1.2.2
    glowstone: ^0.0.2
    package_info: ^2.0.2
    auto_animated: ^3.1.0
    animated_text_kit: ^4.2.2
    glassmorphism: ^3.0.0
    ticket_widget: ^0.0.1
    dotted_line: ^3.1.0
    share_plus: ^6.3.2
    qr_flutter: ^4.0.0
    country_code_picker: ^3.0.0
    shared_preferences: ^2.1.0
    cached_network_image: ^3.2.3
    flutter_cache_manager: ^3.3.0
    fluttertoast: ^8.2.1
#    provider: ^6.0.5
    intl_phone_number_input: ^0.7.0+2
    video_player: ^2.2.5
    flutter_custom_clippers: ^2.1.0
    assets_audio_player: ^3.1.1
    model_viewer_plus: ^1.6.1
    flutter_linkify: ^6.0.0
    flutter_dotenv: ^5.1.0
    timer_count_down: ^2.2.2
    circular_countdown_timer: ^0.2.3


dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0
    dart_code_metrics: ^5.6.0
    flutter_launcher_icons: ^0.13.1

flutter_icons:
    android: true
    ios: true
    image_path: "assets/images/APPICON_DARK.png"

flutter:
    uses-material-design: true

    assets:
        - assets/images/
        - assets/video/
        - assets/audios/halloween_sound.mp3
        - assets/3D/pumpkin.glb
        - assets/3D/Skull.glb
        - lib/.env

    fonts:
        - family: Roboto
          fonts:
              - asset: assets/fonts/Roboto-Regular.ttf
        - family: Quicksand
          fonts:
              - asset: assets/fonts/Quicksand-Regular.ttf
              - asset: assets/fonts/Quicksand-Bold.ttf
                weight: 700
        - family: Panther
          fonts:
              - asset: assets/fonts/Panther.ttf
        - family: Danger-Night
          fonts:
              - asset: assets/fonts/Danger-Night.ttf
        - family: Gothica-Book
          fonts:
              - asset: assets/fonts/Gothica-Book.ttf
